[package]
name = "chip-8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.11", default-features = false, features = ["macros"] }
rand = "0.8.5"
sdl2 = "0.36"
